### ISSUE TITLE
Feature: Ability to refresh playlists

### ISSUE THREAD

**Issue by DavisNT** [pimusicbox/mopidy-musicbox-webclient#107]
I would like to add ability to refresh existing playlists.

Playlists could have a _Refresh_ button in the top of screen (like queue has _Clear_ button). The _Refresh_ button would signal Mopidy to refresh existing playlists.

:question: Is such feature welcome? If yes, I will investigate it and, possibly, create a Pull Request.

**Comment by kingosticks** [comment]
I think (I might be wrong) that mopidy provides some sort of playlist
changed events. I think we probably want to be listening for these and
updating automatically rather than proving another button in the main ui.
If we did want to force a refresh, I'd be inclined to bury this button
somewhere less prominent.

**Comment by DavisNT** [comment]
No, Mopidy does **not** always properly refresh playlists on its own. It provides a method for refreshing playlists (see https://docs.mopidy.com/en/v0.19.5/api/core/#mopidy.core.PlaylistsController.refresh ).

I have had issues with playlists newly created in Spotify (not mentioning that I have to restart Mopidy whenever I create a new .m3u file locally), I assume that other users are frustrated by these issues too. Are you 100% sure that _Refresh_ button here is not welcome? I don't think such button will hurt anyone, but I assume it might be an easy-to-use workaround if some Mopidy backends do not automatically/properly refresh playlists.

Also I assume that **may be** it will turn out that playlist refresh must be initiated after every playlist save.

**Comment by kingosticks** [comment]
The lack of Spotify playlist refreshing it's an issue in mopidy-spotify
itself and it's not a good indicator of what the Mopidy playlists
system/API does. It's actually fixed in the upcoming 2.0 release anyway.

All playlist creation/modification support has only recently been looked at
properly so we should start to see some improvements in this area. If there
really is no playlist modify event in the current API we should probably
request something.

Doing a playlist refresh after we do a save is of course reasonable but it
doesn't help when the modification was done in a different client. I'll
have a closer look at this later and get back to you.

**Comment by kingosticks** [comment]
Looks like the playlist_changed event should do us just fine. As I said
before, it's broken in mopidy-spotify and probably the reason nobody has
really bothered supporting it before. I agree it is currently very
frustrating but the new fixed version is due soon. I don't think we
currently listen for this event so there is something to be done here.

**Comment by DavisNT** [comment]
I think much worse issue is playlists not being refreshed in Mopidy (from backends). I was originally talking about this issue. And offered to create _Refresh_ button. If Mopidy-Spotify will have automatic refresh from Spotify fixed, then this issue becomes much less common. If you think that we could create such button (and bury it somewhere), then I am willing to create it.

I thing that playlists not being refreshed in Webclient (from Mopidy) is a minor issue, because there is a simple and intuitive workaround - reloading the page. So I am not planning to work on this (at least for now).

**Comment by kingosticks** [comment]
I suggest you install mopidy-spotify v2 and see what webclient improvements
are still needed. That's the version we need to be working towards
supporting. If there are issues using that then we can go from there. To
me, this is a ui workaround for outdated backend software.

**Comment by DavisNT** [comment]
I have had some other issues with Mopidy-Spotify 2.0 and I will most likely do more testing (and report spotted issues).

But this workaround is anyway needed if local playlists are changed directly in the filesystem (i.e. `.m3u` files added/deleted/edited).
Currently I am manually pasting `mopidy.playlists.refresh()` in JavaScript console of the browser to do the refresh (a button for this would be much more convenient :wink:). However manually editing local playlists is a bit geeky and I do not know how many Musicbox Webclient users do this.

**Comment by kingosticks** [comment]
Please do report any issues with m-s2. 

That is an excellent point regarding people making changes to local playlists. And since we don't offer a way to modify playlists in the UI it seems very reasonable to support this. I guess mopidy-m3u might ideally watch the folder for changes (somehow avoiding an infinite loop of changes triggering changes) but I don't think there are any plans for that right now.

If we can get a [small refresh icon](http://fortawesome.github.io/Font-Awesome/icon/refresh/) in somewhere (rather than a big button) that would be nice.

**Comment by DavisNT** [comment]
Okie, I will add the icon.
What do you think about adding this icon below the list of playlists (in lower left corner of playlists form)?

**Comment by kingosticks** [comment]
Does that mean if you have a lot of playlists you'll have to scroll down to
see it? I suppose that sort of hides it. Or we could have it right aligned
by the playlists link in the side navigation. That would be a lot more
prominent and goes against what I was saying before, but the use case of
external editing is actually pretty solid.

**Comment by DavisNT** [comment]
I didn't quite get you. Did you meant adding a caption line (like _Queue_ has) and instead of button adding refresh icon?
