### ISSUE TITLE
Let users choose default click action

### ISSUE THREAD

**Issue by ttheuer** [pimusicbox/mopidy-musicbox-webclient#133]
As discussed [here](https://github.com/pimusicbox/mopidy-musicbox-webclient/pull/36), the default action of replacing the whole queue with all tracks is not universally preferred.

I would like to see an option (either saved in the browser, or - preferably - set on the "server", in a line of code, maybe) to have the default click action be "Add to bottom of queue".

I tried to apply the pull-request myself, but the codebase has changed too much, apparently, and I am not familiar enough with it, to know where changes have to be made.

**Comment by ttheuer** [comment]
Is there anything I can do to help this along?  
I looked at the code myself, but I'd have to invest a day or more to acquaint myself with it, so I'd rather leave it to someone who knows what they're doing :)

**Comment by jcass77** [comment]
I've had a quick look and unfortunately there does not appear to be one single place in the codebase where you could effect this change: MMW currently uses multiple 'play' functions in various locations.

We're slowly working our way through the backlog of issues but in the interim you could try searching for ``playTrack...`` to get a sense of where the changes will be required if you would like to fix this yourself. You're probably looking to modify the ``mopidy.tracklist.add`` calls to just add the track that you clicked on instead of the entire list.
