### ISSUE TITLE
search not working (properly)

### ISSUE THREAD

**Issue by tcurdt** [pimusicbox/mopidy-musicbox-webclient#160]
I am playing a track from "Sense Field" on Spotify while writing this, yet searching for "Sense Field" does not show any artists at all. No even when searching for "Sense". It does return a few tracks though - but it's way too slow to be usable.

> Did you try to limit the search to spotify only? Slow backends are mostly out of our control.

Yes, that didn't help.

**Comment by jcass77** [comment]
If this is only a problem when searching Spotify, then you may be experiencing one of a number of search issues that occurred when Spotify changed their API recently: see https://github.com/mopidy/mopidy-spotify/issues/89?

If so we can probably close the issue here in anticipation of it being resolved in Mopidy-Spotify - I see a PR has already been proposed for this.
