### ISSUE TITLE
[request enhancement] Get Custom Image Display with custom m3u

### ISSUE THREAD

**Issue by oouuppss** [pimusicbox/mopidy-musicbox-webclient#188]
Got an m3u who doesnt have some png/jpg display while listening to it.
What is the way to add custom links/html/png/jpg to it.

**Comment by jcass77** [comment]
MMW should be displaying the relevant album cover art as each track in the playlist is being played.

It first tries to retrieve the image from Mopidy via whatever backend is serving the track, and falls back to searching for the album and track name on last.fm if that fails.

If none of the above is available for the tracks that you are playing then you may have to edit the tags manually first, unless I am misunderstanding the requirement?

If you could provide a little more detail of what the m3u contains then it should be possible to identify which backend should be providing the track images.

Showing images on an m3u playlist level (and not for individual tracks) is not currently supported in Mopidy as far as I am aware and as such not something that MMW can provide.

**Comment by oouuppss** [comment]
thanx for the answer.
Actually the m3u i'm listening to is one from http://divbyzero.de/index.php/streams
it's an m3u made from an pls file.
Their Icecast server doesn't send track info.
But i could read info from their site, and perhaps pipe it into a file in my system to display it on that missing png.
Thanks anyway ;)
Good works too for this nice front end!

**Comment by oouuppss** [comment]
Same as some tunein station as FIP, only show radio logo, but we could pipe info from radio station on their web page.

**Comment by oouuppss** [comment]
FIP:   tunein:station:s15200

**Comment by jcass77** [comment]
The 'correct' way of doing this might be to implement a small Mopidy backend extension for divbyzero.de (based on mopidy.stream.StreamBackend perhaps) that parses their stream directory web page and adds the relevant tags to the stream as required. Mopidy should then be able to populate the track info from there and in theory it should then show up in MMW (but I am speculating so it might turn out to be more involved than that).

Alternatively, you could probably implement a quick and really nasty hack by editing your ``images.js`` to return a URI to the local file that you piped, and then display the HTML fragment instead of an ``img``.

I'm closing this as I think it is a little too case-specific to end up as a feature in MMW, and as mentioned above you are ideally looking for a backend extension to populate the Mopidy track models properly for the streaming service that you are using.

P.S. There are already [plans afoot](https://github.com/mopidy/mopidy/issues/1474) for enhancing the Tunein extension to include show logos (not sure if that will also cover track information).

**Comment by oouuppss** [comment]
Thank you very much for this good answer.
And again nice works!
