### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by puyamn** [pimusicbox/mopidy-musicbox-webclient#203]
I tried updating with `pip install --upgrade` , but now i can't reach the webclient anymore. Anyone else with the same issue or a solution?

**Comment by kingosticks** [comment]
This will not work on Pi Musicbox, unfortunately there is no upgrade facility yet. 

If you were doing this on a regular Raspbian/Linux install then it should work just fine. If it did not then please post the output of `mopidy deps` and the Mopidy log in `/var/log/mopidy/mopidy.log`.

**Comment by minos314** [comment]
Same problem here. 
I am also interested in updating my Pi Musicbox gui, so are there plans to make it work together?

**Comment by kingosticks** [comment]
There are plans to incorporate updating into the next version but it's a
long way off release (still).

There are notes somewhere about how to manually update individual parts of
the system so that you can run the latest client. I think it's in the wiki
or maybe the discuss forum. But right now it's not something I can invest
time supporting on here.

On 19 Aug 2016 18:49, "minos314" <notifications@github.com> wrote:

Same problem here.
I am also interested in updating my Pi Musicbox gui, so are there plans to
make it work together?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/pimusicbox/mopidy-musicbox-webclient/issues/203#issuecomment-241086970>,
or mute the thread

**Comment by minos314** [comment]
Good news, so i'm looking forward to get the updated version.

In the meantime can you share a link to the manual update notes? I can't find them anywhere.

**Comment by kingosticks** [comment]
Sorry for the delay. http://pimusicbox.readthedocs.io/en/develop/upgrading/
Note, I've no idea if this still works.

Since the OP didn't reply, I don't believe there is any webclient specific issue here and we already have tickets for this in pimusicbox itself. Reopen if I am mistaken.
