### ISSUE TITLE
Using it with Mopidy it keeps searching for Musicbox

### ISSUE THREAD

**Issue by opoloko** [pimusicbox/mopidy-musicbox-webclient#208]
I just installed latest mopidy with a couple of web clients, including Musicbox.

Mopidy starts correctly, but then when trying to use Musicbox web client there's a smally  window saying that is 'looking for musicbox' (although in the conf I left Musicbox to false), and in the browse I can't see any of my services (spotify, youtube, pandora).

Is this a known problem? Anything I can try to fix it?

Thanks!

**Comment by kingosticks** [comment]
That means it cannot connect to the Mopidy server. The message should
really say "looking for mopidy". Do your other Web clients load?

**Comment by opoloko** [comment]
I tried the Mopify one (specialised in Spotify only) and it works. Any log or anything else I can check?

**Comment by kingosticks** [comment]
Very odd, have you set any other musicbox-webclient settings? (most setups
shouldn't need to). In chrome you can open the developer console and see
any errors printed there. Firefox probably has something similar.

On 14 Sep 2016 10:14, "opoloko" <notifications@github.com> wrote:

I tried the Mopify one (specialised in Spotify only) and it works. Any log
or anything else I can check?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pimusicbox/mopidy-musicbox-webclient/issues/208#issuecomment-246953205>,
or mute the thread

**Comment by opoloko** [comment]
Hi thanks for suggestion. Actually I looked back to config and I saw I put some values in the websocket values.

Taking them off and having set the host of http and mpd to :: solved the problem.

I was confused as it says looking for Musicbox (as well in other popups) while maybe it should say 'Mopidy'. Otherwise great job, thanks all working now!

**Comment by kingosticks** [comment]
Yeh I agree it's confusing and definitely a bug.  I've raised https://github.com/pimusicbox/mopidy-musicbox-webclient/issues/209

Thanks!

**Comment by kingosticks** [comment]
Yeh I agree it's confusing and definitely a bug.  I've raised https://github.com/pimusicbox/mopidy-musicbox-webclient/issues/209

Thanks!
