### ISSUE TITLE
Web GUI does not update on playlist changes

### ISSUE THREAD

**Issue by dmosen** [pimusicbox/mopidy-musicbox-webclient#210]
Enivronment:
- Raspbian: Jessie
- Mopidy: 2.0.1 (Is Mopidy 2.x.x already supported?)
- mopidy-musicbox-webclient: 2.3.0

Changing the queue (e.g. adding, removing items) is not reflected in the Web-GUI, i.e. the last state of the queue remains. This happens at least with Firefox (49.0.1) and Chrome (53.0.2785.143 (64-Bit)).

**Comment by kingosticks** [comment]
Yes, Mopidy 2.x.x is supported. 

I am not able to replicate this on Chrome. How exactly are you modifying the queue, using another web  client, using mpd, using some other part of musicbox-webclient? 

I see the queue update as expected when adding songs to the queue from within other parts of musicbox-webclient and using mpc. Do you see any errors/messages in the browser console?

**Comment by dmosen** [comment]
Hi,

I used the functions provided in the web interface to alter the playlist. But for some reason I cannot reproduce this behaviour anymore. Maybe an update or reboot fixed it. 

But now I am facing another issue: Jumping around in the seek bar or switching to the next song makes the music stop sometimes. What I noticed is that - instead of the playtime - '(sync)' is beeing displayed left to the seek bar when it happens. I also checked the browser console but threre are no errors. Actually, I expect this to be a Mopidy related problem, as this also happens when switching tracks via the command line using [mpc](https://linux.die.net/man/1/mpc). Maybe you can tell me at least if this problem also affects you?

Regards,
Dominik

**Comment by kingosticks** [comment]
Does it depend on what backend the music originates from? If I remember correctly, 'sync' is displayed for a second or so while the webclient is requesting the current song position from Mopidy. Once it gets a position update it'll count along on it's own instead of constantly asking for position updates like old versions of the webclient did.

If I click the seek bar or change tracks I see exactly this behaviour and 'seek; very quickly changes to display the time position. Note that I am playing music from Spotify.

If you have problems with the music stopping at all then that cannot be anything to do with a frontend such a musicbox-webclient. If you run Mopidy with more verbose logging enabled if might tell you what's going on, perhaps it's buffering?
