### ISSUE TITLE
Browse: Sort options for Folders first, Tracks first and Mixed

### ISSUE THREAD

**Issue by Caysho** [pimusicbox/mopidy-musicbox-webclient#217]
I have a patch to do sorting on the Browse.
The modifications are to static/js/process_ws.js
I am currently using the Folders first option.

An improvement would be to add a sort selection to the GUI, but I do not know how to go about it.

[process_ws.js.diff.txt](https://github.com/pimusicbox/mopidy-musicbox-webclient/files/659298/process_ws.js.diff.txt)

**Comment by jcass77** [comment]
Is the intention here to have all of the folders listed at the top so that it would be easier for you to browse the various albums in the folder structure?

My feeling is that might be better to rely on something like [Mopidy-Local-SQLite](https://github.com/mopidy/mopidy-local-sqlite), which already caters for this to make browsing easier (and much more).

**Comment by Caysho** [comment]
Yes, folders at the top.
The SQLite extension does albums, not folders, and the result is messy for my collection (e.g. I see years showing up as albums).
A folder in the structure I have could be artist, compilation, genre, date etc.

**Comment by Caysho** [comment]
I spent some time tracing code to figure out where the library data is being generated, and found the mopidy code that sends the details of local directory browsing to clients.

Some initial modifications give the same results as applying the diff I posted.
I will look into making changes there instead, as they are smaller than what is needed here.

**Comment by jcass77** [comment]
Closing this then, in favor of proposing the changes to the Mopidy core.
