### ISSUE TITLE
Excessive Mopidy API calls while buffering

### ISSUE THREAD

**Issue by kingosticks** [pimusicbox/mopidy-musicbox-webclient#237]
When starting to play a radio station the webclient appears to hammer Mopidy with `get_time_position calls` while it's buffering. In the log you can see Mopidy doesn't do anything after 19:41:02,520 until 19:41:10,151 when buffering completes, except respond to our numerous requests. 

This was observed in Mopidy v1.x (Musicbox v0.7.0RC4) so it's possible it's related to some old bug there, I do need to reproduce this in the latest Mopidy.

[Log here](http://dpaste.com/3834ZKG)

**Comment by jcass77** [comment]
This is related to https://github.com/mopidy/mopidy/issues/1420: at the moment, there is no easy way to tell whether a stream is still busy buffering, or if it has actually started to play.

We won't be able to eliminate superfluous ``get_time_position`` calls entirely until the Mopidy core is enhanced to provide audio events that are a little more verbose, instead of having to rely exclusively on ``playbackStateChanged``.

Having said that, it should be possible to at least reduce the rate at which ``get_time_position`` is called to something more sensible (i.e. once every 500ms or so).
