### ISSUE TITLE
Wrong file icon for audio files in file extension

### ISSUE THREAD

**Issue by jemand771** [pimusicbox/mopidy-musicbox-webclient#246]
I know how confusing that title sounds.

When using the search function, there is a little file-thing icon next to every track (on the left).  In the file extension (browse -> Files) every folder has a folder icon. But somehow, every mp3 file has this icon too.
The play icons on the right of the tracks are correct though. (folders are not playable)

I'm not sure if this is how it's meant to be.

I didn't test this with other file formats. Screenshots and config following.

Play icons when searching
![unbenannt](https://user-images.githubusercontent.com/19669567/28268235-ba0c56f0-6afd-11e7-87bb-95fad8c130a0.PNG)

Folder icons in file extension (those are all folders indeed)
![unbenannt](https://user-images.githubusercontent.com/19669567/28268271-e4b25f12-6afd-11e7-9511-507ed7412c6e.PNG)

Folder icons on mp3 files
![unbenannt](https://user-images.githubusercontent.com/19669567/28268298-03285546-6afe-11e7-83b8-865a42c9d1f6.PNG)

output of `mopidy config` (not sure if this matters)
```
[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
color = true
console_format = %(levelname)-8s %(message)s
debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
debug_file = mopidy.log
config_file =

[audio]
mixer = software
mixer_volume =
output = autoaudiosink
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[youtube]
enabled = true

[mpd]
enabled = true
hostname = 0.0.0.0
port = 6600
password =
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist =
  listall
  listallinfo
default_playlist_scheme = m3u

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

[m3u]
enabled = true
base_dir = $XDG_MUSIC_DIR
default_encoding = latin-1
default_extension = .m3u8
playlists_dir =

[softwaremixer]
enabled = true

[file]
enabled = true
media_dirs =
  /media/pi/willys/music/
excluded_file_extensions =
  .jpg
  .jpeg
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[local]
enabled = true
library = sqlite
media_dir = /media/pi/willys/music/
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt
  .webm

[musicbox_webclient]
enabled = true
musicbox = true
websocket_host =
websocket_port =
on_track_click = PLAY_ALL

[local-sqlite]
enabled = true
directories =
  Albums                  local:directory?type=album
  Artists                 local:directory?type=artist
  Composers               local:directory?type=artist&role=composer
  Genres                  local:directory?type=genre
  Performers              local:directory?type=artist&role=performer
  Release Years           local:directory?type=date&format=%25Y
  Tracks                  local:directory?type=track
  Last 24h's Updates      local:directory?max-age=86400
  Last Week's Updates     local:directory?max-age=604800
  Last Month's Updates    local:directory?max-age=2592000
timeout = 10
use_album_mbid_uri = true
use_artist_mbid_uri = false
use_artist_sortname = false
```

**Comment by kingosticks** [comment]
Yeh, I know exactly what you mean. @jcass77 did change this not so long ago but I ended up reverting it before the release. I don't recall the specifics now, I'll have to go back and remind myself but I think it was because the implementation we ended up with had all playable tracks as the same icon, regardless of what backend they were from. What we have now is still far from ideal so this is a valid issue, assuming we don't already have one for it.

**Comment by jcass77** [comment]
The behaviour that you are describing was used in a previous release; the same icon was used next to both playable tracks and the backend extension in the root folder of 'Browse'. I thought this would be cool because it would enable you to know which backend extension was serving up the track just by looking at it when it showed up in search results.

This ended up being confusing however because the standard folder icon was also used for the 'Files' extension (and hence, any playable tracks that it contained), which is why I think @kingosticks changed it. 

Are you sure that you are using the latest version of MMW? If you upgraded recently then you may have to clear your browser cache.

I could not replicate this issue in the latest release. Please re-open if you still have any problems after upgrading.
