### ISSUE TITLE
Now playing does not update stream title

### ISSUE THREAD

**Issue by hasifantasy** [pimusicbox/mopidy-musicbox-webclient#259]
In the pimusicbox Web Frontend is no update of the stream title. The method core.playback.get_stream_title from the mopidy core library gives exactly the information needed, but there is no function implemented to call this from the "now Playing" view in the web frontend. Seems to me that this is "...one small step for man, one giant leap for mankind." :-)

**Comment by kingosticks** [comment]
Thanks, good suggestion.

**Comment by the-x-at** [comment]
Hi @kingosticks, some time ago I discovered the same issue when running pimusicbox and wanted to fix it by myself. Turned out it's an already known issue and you have been working on it a while ago, but somehow it appears your initial steps have not made it into the development branch. Would be great to see it there.

**Comment by kingosticks** [comment]
Wow! Yes, It seems I opened a PR and then never merged it. I've no idea why not, what a screw-up. Thanks very much for highlighting that. I've just merged it into develop and I'll cut a release
