### ISSUE TITLE
Show the IP-Adress of the musicbox-server in webclient 

### ISSUE THREAD

**Issue by chrisgo67** [pimusicbox/mopidy-musicbox-webclient#67]
Hi,

from my point of view it would be very handy to make the current IP-Adress of the musicboxserver visible in the Webclient.

Regards

Chris

**Comment by kingosticks** [comment]
I don't believe you can get this in javascript so it's non-trivial to implement. Out of interest, why do you need this? Isn't the hostname sufficient?

**Comment by chrisgo67** [comment]
Hi, my intention beheind this is that older android devices don't seem to have the abillity to resolve names via DNS properly. My s4 active does handle this fine but the s3 minis of my wife and children do not. So it would help me to tell them the IP-Adr. to get connected.
btw. my studip new router is not able to give fixed IP-Adresses via DHCP (infinite leases time).

I think showing the servers IP-Address would have to be implemented on the serverside, or am i worng?

Chris

**Comment by adamcik** [comment]
Try https://play.google.com/store/apps/details?id=com.dz0ny.mopidy perhaps?

**Comment by kingosticks** [comment]
You are entirely correct. The issue is that musicbox-webclient is currently a 'static' web extension that's written entirely in javascript, as opposed to an 'app' that uses templates/serverside code like some of the other web extensions. It's a simple enough change and it would open the door to some more features so it's certainly worth doing. Someone just needs to do it! 

But actually, it might make more sense if added to https://github.com/woutervanwijk/mopidy-websettings, which is already an 'app'.

**Comment by kingosticks** [comment]
+1 for adamcik's suggestion. But old android devices might have even more problems with mdns auto-discovery!

**Comment by chrisgo67** [comment]
Thank you very much for these tips.
I'll try them definitly as soon as i can.
I'll give you feedback!

**Comment by kingosticks** [comment]
Following https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/commit/b94db6bfccd41d53b77c8e32b56d0cc9fca32471 this is now simple to do. Where should this information go?
