### ISSUE TITLE
Add whole playlist, folder or album to the queue.

### ISSUE THREAD

**Issue by EHLOVader** [pimusicbox/mopidy-musicbox-webclient#69]
The triple dot menus don't appear on the above items anywhere. It would be nice to add entire lists of things at once to the queue.

**Comment by kingosticks** [comment]
Doesn't clicking the 'above item' do that?

**Comment by EHLOVader** [comment]
I see now, you can use "Add all to bottom of queue" I think it would be nice to have the menus attached to the side of the parent item. OR in the header of the parent item.

Also perhaps wording might help. Is All the entire page, or just this album in the artist or search results?

![Add all to bottom of queue](https://i.imgur.com/sfxnhRcm.png)

I would like to see the dots over here instead. 

![Playlist item](https://i.imgur.com/OCKRLfNm.png)

and possibly something up here in the album header.

![Album header](https://i.imgur.com/QRLalfDm.png)

**Comment by jcass77** [comment]
The convention that we are following at the moment is that all tracklist actions should originate from the popup menus linked to a track, rather than having additional menus in the UI that users have to go and look for on every pane.

Once https://github.com/pimusicbox/mopidy-musicbox-webclient/pull/193 is merged, we'll have all of the actions available wherever a track is rendered as part of a list, so this functionality should be a lot more consistent.

The only feature that I think you may be missing in the latest release is the ability to add just the tracks of a specific album to the queue. This can be done with two clicks if you select the 'Show Album...' option, and then 'Play All' on the screen that follows. I'd prefer using this approach rather than adding yet another option to the popup menus, which are becoming rather long and cumbersome as it is.

I'm closing this as I think all of the requests have been addressed (if not also provided for in the code since the issue was logged originally).
